
"""
Application-wide constants for GameDev Hub.
"""

# Game identifiers
GAME_SNAKE = "snake"
GAME_TICTACTOE = "tictactoe"
GAME_MEMORY = "memory"
GAME_BREAKOUT = "breakout"
GAME_PONG = "pong"
GAME_ASTEROIDS = "asteroids"
GAME_FLAPPY = "flappy"
GAME_TETRIS = "tetris"
GAME_PACMAN = "pacman"
GAME_RACING = "racing"

ALL_GAMES = [
    GAME_SNAKE, GAME_TICTACTOE, GAME_MEMORY, GAME_BREAKOUT, GAME_PONG,
    GAME_ASTEROIDS, GAME_FLAPPY, GAME_TETRIS, GAME_PACMAN, GAME_RACING,
]

# Score limits
MIN_SCORE = 0
MAX_SCORE = 1_000_000
MAX_NAME_LENGTH = 20
MAX_LEADERBOARD_ENTRIES = 100
DEFAULT_LEADERBOARD_LIMIT = 20

# Rate limiting
RATE_LIMIT_REQUESTS = 100
RATE_LIMIT_WINDOW_SECONDS = 60

# Session
SESSION_TTL_SECONDS = 3600
MAX_ACTIVE_SESSIONS = 10_000

# Pagination
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

# Difficulties
DIFFICULTY_EASY = "easy"
DIFFICULTY_MEDIUM = "medium"
DIFFICULTY_HARD = "hard"
DIFFICULTY_EXPERT = "expert"
ALL_DIFFICULTIES = [DIFFICULTY_EASY, DIFFICULTY_MEDIUM, DIFFICULTY_HARD, DIFFICULTY_EXPERT]

# API
API_PREFIX = "/api"
HEALTH_PATH = "/api/health"

# HTTP
HTTP_OK = 200
HTTP_CREATED = 201
HTTP_BAD_REQUEST = 400
HTTP_NOT_FOUND = 404
HTTP_RATE_LIMITED = 429
HTTP_SERVER_ERROR = 500
